FROM python:3.8
ENV PYTHONUNBUFFERED 1
RUN apt-get update && apt-get install
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN python3 -m pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /code/
EXPOSE 8000
CMD ./start_server.sh
