SHELL := /bin/bash

test:
	python manage.py test loan

shell:
	python manage.py shell

makemigrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate

freeze_requirements:
	pip freeze > requirements.txt