# Generated by Django 4.2 on 2023-05-28 12:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lib.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('due_date', models.DateField()),
                ('suggested_emi', models.FloatField()),
                ('status', models.CharField(choices=[('UNPAID', 'unpaid'), ('PARTIALLY_PAID', 'partially paid'), ('PAID', 'paid')], default='UNPAID', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.installment')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('tenure', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(60), lib.validators.validate_nonzero])),
                ('periodicity', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('COMPLETED', 'completed'), ('WRITTEN_OFF', 'loan written-off'), ('SETTLED', 'loan settled'), ('HOLD', 'hold')], max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('interest', models.DecimalField(decimal_places=5, help_text='1 means 100%', max_digits=6)),
                ('processing_fee', models.DecimalField(decimal_places=5, help_text='1 means 100%', max_digits=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=5, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('COMPLETED', 'completed'), ('WRITTEN_OFF', 'loan written-off'), ('SETTLED', 'loan settled'), ('HOLD', 'hold')], max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=30, unique=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('installments', models.ManyToManyField(through='loan.InstallmentDetail', to='loan.installment')),
                ('loanshare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanshare')),
            ],
        ),
        migrations.AddField(
            model_name='installmentdetail',
            name='loan_repayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanrepayment'),
        ),
        migrations.AddField(
            model_name='installment',
            name='loanshare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanshare'),
        ),
    ]
