# Generated by Django 4.2 on 2023-05-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loan_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='suggested_emi',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
