# Generated by Django 4.2 on 2023-05-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_installment_suggested_emi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.installment')),
            ],
        ),
    ]
