# Generated by Django 4.2 on 2023-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_installment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
